# Generated by Django 3.0.5 on 2020-04-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=16)),
                ('last_read', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=67)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Mailbox')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Station')),
            ],
        ),
        migrations.AddField(
            model_name='mailbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Station'),
        ),
        migrations.CreateModel(
            name='ChatSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Chat')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Station')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Chat')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Station')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Station'),
        ),
    ]
