# Generated by Django 3.0.5 on 2020-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='topic',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
