# Generated by Django 3.0.5 on 2020-04-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_chat_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=512),
        ),
    ]
