# Generated by Django 3.0.5 on 2020-04-21 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200421_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, max_length=512, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Station')),
            ],
        ),
    ]
