# Generated by Django 3.0.5 on 2020-04-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
