# Generated by Django 3.0.5 on 2020-05-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200425_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='pounce',
            field=models.BooleanField(default=False),
        ),
    ]
