# Generated by Django 3.0.5 on 2020-05-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_station_pounce'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='pounce',
            field=models.BooleanField(default=False),
        ),
    ]
