# Generated by Django 3.0.5 on 2020-05-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_mailbox_pounce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailbox',
            old_name='pounce',
            new_name='unread',
        ),
    ]
